in __destruct()
NULL
in __destruct()
NULL
in __destruct()
object(Evil)#4 (0) {
}
Caught: Continuation is already running
in __destruct()
NULL
Caught: Continuation is already finished
Finished!
Returned from main safely
